server:
  port: 8082
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses:localhost:5672
    virtual-host: app_vhost
    username:username
    password:password
  zipkin:
    baseUrl: http://localhost:9411/
    enabled:true
    sender:
      type:rabbit
      enabled:true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
