server:
  port: 8082
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  rabbitmq:
    username:guest
    password:guest
    host: http://localhost:5672
    port: 5672
    
queue:
  movie:
    name: Movie
  serie:
    name: Serie
 
resilience4j:
  circuitbreaker:
    instances:
      series:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false 
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
      
management:
  health:
    circuitbreakers:
      enabled: true
