server:
  port: 8080

spring:
  application:
    name: gateway-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: http://localhost:8082/
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: http://localhost:8080/fallback/catalog
        - id: movieRoute
          uri: http://localhost:8083/
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: http://localhost:8080/fallback/movies
        - id: seriesRoute
          uri: http://localhost:8084/
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: http://localhost:8080/fallback/series
        
resilience4j:
  circuitbreaker:
    instances:
      series:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false 
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false        
  retry:
    instances:
      series:
        maxAttempts: 3
        waitDuration: 1000
        retryException[0]: feign.FeignException$InternalServerError
      movies:
        maxAttempts: 3
        waitDuration: 1000
        retryException[0]: feign.FeignException$InternalServerError
management:
  health:
    circuitbreakers:
      enabled: true
