server:
  port: 8080

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: http://localhost:8082/
          predicates:
            - Path=/movies/**
          filters:
            - AddRequestHeader=user-request-header, testing-headers
            - AddResponseHeader=user-response-header, testing-response-header
        - id: catalogRoute
          uri: http://localhost:8083/
          predicates:
            - Path=/catalog/**
