server:
  port: 8083
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:movie-service.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses:localhost:5672
    virtual-host: app_vhost
    username:username
    password:password
  zipkin:
    baseUrl: http://localhost:9411/
    enabled:true
    sender:
      type:rabbit
      enabled:true
